# Generated by Django 2.2.2 on 2020-04-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_persongroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonGroup',
        ),
    ]
