# Generated by Django 2.2.2 on 2020-04-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование офиса')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование переговорной')),
                ('size', models.IntegerField(verbose_name='Вместимость')),
                ('availability', models.BooleanField(verbose_name='Доступность для бронирования')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Office', verbose_name='Офис')),
            ],
            options={
                'verbose_name': 'Переговорная',
                'verbose_name_plural': 'Переговорные',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_type', models.CharField(max_length=80, verbose_name='Тип оборудования')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Office', verbose_name='Офис')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['eq_type'],
            },
        ),
    ]
