# Generated by Django 2.2.2 on 2020-05-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='office',
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room', verbose_name='Переговорная'),
            preserve_default=False,
        ),
    ]
