# Generated by Django 2.2.2 on 2020-05-01 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема встречи')),
                ('start_meeting_time', models.DateTimeField(verbose_name='Время начала встречи')),
                ('end_meeting_time', models.DateTimeField(verbose_name='Время окончания встречи')),
                ('create_reservation_time', models.DateTimeField(verbose_name='Время создания бронирования')),
                ('cancel_reservation_time', models.DateTimeField(verbose_name='Время отмены бронирования')),
                ('state', models.CharField(choices=[('0', 'В ожидании подтверждения'), ('1', 'Подтверждена'), ('2', 'Отменена')], default='1', max_length=1, verbose_name='Состояние бронирования')),
                ('state_canceled', models.CharField(choices=[('0', 'Ручная отмена'), ('1', 'Автоматическая отмена'), (None, 'Не отменена')], default=None, max_length=1, verbose_name='Состояние отмены брони')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор встречи')),
                ('invited', models.ManyToManyField(default=None, null=True, related_name='invited', to=settings.AUTH_USER_MODEL, verbose_name='Участники встречи')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room', verbose_name='Переговорная')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['start_meeting_time'],
            },
        ),
    ]
