# Generated by Django 2.2.2 on 2020-05-17 14:34

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема встречи')),
                ('start_meeting_time', models.DateTimeField(verbose_name='Время начала встречи')),
                ('end_meeting_time', models.DateTimeField(verbose_name='Время окончания встречи')),
                ('cancel_reservation_time', models.DateTimeField(blank=True, null=True, verbose_name='Время отмены бронирования')),
                ('state', models.CharField(blank=True, choices=[('0', 'В ожидании подтверждения'), ('1', 'Подтверждена'), ('2', 'Отменена')], default='0', max_length=1, null=True, verbose_name='Состояние бронирования')),
                ('state_canceled', models.CharField(blank=True, choices=[('0', 'Ручная отмена'), ('1', 'Автоматическая отмена'), (None, 'Не отменена')], default=None, max_length=1, null=True, verbose_name='Состояние отмены брони')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['start_meeting_time'],
            },
        ),
    ]
