# Generated by Django 2.2.2 on 2020-05-17 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор встречи'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='invited',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='invited', to=settings.AUTH_USER_MODEL, verbose_name='Участники встречи'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room', verbose_name='Переговорная'),
        ),
    ]
