# Generated by Django 2.2.2 on 2020-05-01 15:31

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='create_reservation_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('0', 'В ожидании подтверждения'), ('1', 'Подтверждена'), ('2', 'Отменена')], default='0', max_length=1, verbose_name='Состояние бронирования'),
        ),
    ]
