# Generated by Django 2.2.2 on 2020-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200517_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cancel_reservation_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время отмены бронирования'),
        ),
    ]
