# Generated by Django 2.2.2 on 2020-05-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20200506_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cancel_reservation_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время отмены бронирования'),
        ),
    ]
